/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/native_window.h>
#include <android/native_window_jni.h>
#include "camera_preview/mv_recording_preview_controller.h"
#include <sys/types.h>
#include <android/asset_manager_jni.h>
#include <android/asset_manager.h>
/* Header for class com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler */

#ifndef _Included_com_jingju_videorecorder_songstudio_recording_camera_preview_ChangbaRecordingPreviewScheduler
#define _Included_com_jingju_videorecorder_songstudio_recording_camera_preview_ChangbaRecordingPreviewScheduler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_changba_songstudio_recording_camera_preview_RecordingPreviewScheduler
 * Method:    switchPreviewFilter
 * Signature: (ILjava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_switchPreviewFilter__ILandroid_content_res_AssetManager_2Ljava_lang_String_2
  (JNIEnv *, jobject, jint, jobject, jstring);

JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_adaptiveVideoQuality
  (JNIEnv *, jobject, jint, jint, jint);

JNIEXPORT void JNICALL
Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_hotConfigQuality(
        JNIEnv *env, jobject instance,jint max, jint avg, jint fps);

/*
 * Class:     com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler
 * Method:    switchCameraFacing
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_switchCameraFacing
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_startEncoding
  (JNIEnv *, jobject, jint, jint, jint, jint, jboolean, jint);

JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_stopEncoding
  (JNIEnv *, jobject);
/*
 * Class:     com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler
 * Method:    prepareEGLContext
 * Signature: (Ljava/lang/Object;II)V
 */
JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_prepareEGLContext
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler
 * Method:    resetRenderSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_resetRenderSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler
 * Method:    destroyEGLContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_destroyEGLContext
  (JNIEnv *, jobject);

/*
 * Class:     com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler
 * Method:    notifyFrameAvailable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_notifyFrameAvailable
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_updateTexMatrix
  (JNIEnv *, jobject, jfloatArray);

JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_switchPauseRecordingPreviewState
  (JNIEnv* env, jobject obj);

JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_switchCommonPreviewState
  (JNIEnv* env, jobject obj);

JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_createWindowSurface
  (JNIEnv*, jobject, jobject);

JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_destroyWindowSurface
  (JNIEnv*, jobject);

JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_setBeautifyParam(JNIEnv* env, jobject, jint, jfloat);
JNIEXPORT void JNICALL Java_com_jingju_videorecorder_songstudio_recording_camera_preview_RecordingPreviewScheduler_hotConfig
        (JNIEnv *env, jobject obj, jint bitRate, jint fps, jint gopSize);

#ifdef __cplusplus
}
#endif
#endif
